name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (frontend)
        run: npm install
        working-directory: ./med-hub-web

      - name: Build frontend
        run: npm run build
        working-directory: ./med-hub-web

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./med-hub-web/dist
          # optional: keep history of deployments
          keep_files: false

  # The `deploy-pages` job is provided by GitHub; after the artifact is uploaded it will be deployed.